services:
  chaptarr:
    image: robertlordhood/chaptarr:latest
    container_name: chaptarr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
    volumes:
      - /volume1/docker/books/chaptarr/config:/config
      - /volume1/docker/books/ebooks:/books
      - /volume1/docker/books/audiobooks:/audiobooks
      - /volume1/docker/qbit/data/manual/complete:/data/manual/complete
    ports:
      - 8789:8789
    restart: "unless-stopped"
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /volume1/docker/qbit/data/manual/complete:/audiobooks
      - /volume1/docker/books/podcasts:/podcasts
      - /volume1/docker/books/config:/config
      - /volume1/docker/books/metadata:/metadata
    environment:
      - TZ=America/Los_Angeles