---
version: '3'

services:
  deluge:
    image: ghcr.io/binhex/arch-delugevpn:2.1.1-8-03
    labels:
      org.opencontainers.image.authors: binhex
      org.opencontainers.image.source: https://github.com/binhex/arch-delugevpn
    container_name: deluge
    cap_add:
      - NET_ADMIN
    environment:
      - DELUGE_DAEMON_LOG_LEVEL=info
      - DELUGE_WEB_LOG_LEVEL=info
      - ENABLE_PRIVOXY=no
      - HOME=/home/nobody
      - LAN_NETWORK=192.168.86.0/24
      - LANG=en_GB.UTF-8
      - NAME_SERVERS=84.200.69.80,37.235.1.174,1.1.1.1,37.235.1.177,84.200.70.40,1.0.0.1
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - PGID=0
      - PUID=0
      - STRICT_PORT_FORWARD=no
      - TERM=xterm
      - UMASK=000
      - VPN_CLIENT=openvpn
      - VPN_ENABLED=yes
      - VPN_INPUT_PORT=1234
      - VPN_OUTPUT_PORTS=5678
      - VPN_PASS=FISHouttawater92*
      - VPN_PROV=custom
      - VPN_USER=yaimalex@gmail.com
      # - VPN_OPTIONS=--script-security 2 --up /config/tun_up.sh
    ports:
      - 58846:58846
      - 58946:58946
      - 58946:58946/udp
      - 8112:8112
      - 8118:8118
      - 42522:42522
    volumes:
      - /volume1/docker/delugevpn/config:/config
      - /volume1/docker/delugevpn/data:/data
    restart: unless-stopped