---
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /volume1/docker/bazarr/config:/config
      - /volume1/Movies:/movies #optional
      - /volume1/TV Shows:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped